-- Q1 What is the total sales generated by the store?

SELECT SUM(sales::numeric) AS total_sales 
FROM orders;

-- Q2 How are sales trending over time (monthly)?

SELECT DATE_TRUNC('month',order_date::date) AS month,
SUM(sales::numeric) AS total_sales 
FROM orders
GROUP BY DATE_TRUNC('month',order_date::date)
ORDER BY month;

-- Q3 How do sales compare year over year?

SELECT DATE_TRUNC('year',order_date::date) AS year,
SUM(sales::numeric) AS total_sales 
FROM orders
GROUP BY DATE_TRUNC('year',order_date::date)
ORDER BY year;

-- Q4 Which product categories generate the highest sales?

SELECT category, SUM(sales::numeric) AS total_sales
FROM orders 
GROUP BY category
ORDER BY total_sales DESC;

-- Q5 Which sub-categories drive sales within each category?

SELECT category, sub_category, total_sales,
RANK() OVER(PARTITION BY category ORDER BY total_sales DESC) AS category_rank
FROM (
SELECT category, sub_category, SUM(sales::numeric) AS total_sales
FROM orders
GROUP BY category, sub_category)
ORDER BY category_rank
;


-- Q6 Which regions generate the highest sales?

SELECT region,SUM(sales::numeric) AS total_sales
FROM orders
GROUP BY region
ORDER BY total_sales DESC;

-- Q7 Which are the top 10 states by total sales?

SELECT state,SUM(sales::numeric) AS total_sales
FROM orders
GROUP BY state
ORDER BY total_sales DESC
LIMIT 10;

--Q8 Who are the top 10 customers by total sales?

SELECT customer_id, customer_name, SUM(sales::numeric) AS total_sales
FROM orders
GROUP BY customer_id, customer_name
ORDER BY total_sales DESC
LIMIT 10;

--Q9 How does sales vary across customer segments?

SELECT segment,SUM(sales::numeric) AS total_sales
FROM orders
GROUP BY segment
ORDER BY total_sales DESC;

-- Q10 Sales concentration analysis (Top 20% customers vs others)

WITH customer_sales AS (
  SELECT
    customer_name,
    SUM(sales::numeric) AS total_sales
  FROM orders
  GROUP BY customer_name
),
ranked_customers AS (
  SELECT
    customer_name,
    total_sales,
    NTILE(5) OVER (ORDER BY total_sales DESC) AS customer_bucket
  FROM customer_sales
)
SELECT
  customer_bucket,
  SUM(total_sales) AS bucket_sales
FROM ranked_customers
GROUP BY customer_bucket
ORDER BY customer_bucket;



